version: '3.8'

services:
    mysql:
        command:
            -   "--ssl=0"
            - "--default-authentication-plugin=mysql_native_password"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-root}"]
            retries: 5
            interval: 30s
            start_period: 80s
            timeout: 60s
        image: mysql:8.0.32
        restart: always
        volumes:
            -   mysql:/var/lib/mysql


    webserver:
        command: >
            /bin/sh -c "export FASTCGI_PASS_HOST=laravel SERVER_LISTEN_PORT=80 &&
                envsubst '$$FASTCGI_PASS_HOST $$SERVER_LISTEN_PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf &&
                exec nginx -g 'daemon off;'"
        image: nginx:alpine
        depends_on:
            -   laravel
        ports:
            -   ${LARAVEL_PUBLISHED_PORT:-8000}:80
        volumes:
            -   ./:/app:ro
            -   ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            -   ./docker/nginx/conf.d/nginx.template:/etc/nginx/conf.d/default.template

    laravel:
        build:
            context: ./
            dockerfile: docker/Dockerfile
            args:
                PHP_VERSION: ${PHP_VERSION:-8.1}
            target: dev
        depends_on:
            -   mysql
        environment:
            DB_HOST: ${DB_HOST:-mysql}
            DB_PORT: ${DB_PORT:-3306}
            DB_DATABASE: ${DB_DATABASE:-laravel_starter}
            DB_USERNAME: ${DB_USERNAME:-root}
            DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MAIL_MAILER:
            MAIL_HOST:
            MAIL_PORT:
            MAIL_USERNAME:
            MAIL_PASSWORD:
            MAIL_ENCRYPTION:
            MAIL_FROM_ADDRESS:
            MAIL_FROM_NAME:
        healthcheck:
            test: ["CMD-SHELL", "curl --fail -s 'http://nginx/monitor/health/checks' || exit 1"]
            start_period: 60s
            interval: 10s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            -   ./:/app:rw


    adminer:
        depends_on:
            - mysql
        image: adminer
        ports:
            - ${ADMINER_PUBLISHED_PORT:-9090}:8080
        restart: always


volumes:
    mysql:
